#!/bin/bash

apt update

# Install required packages
apt install -y build-essential wget git autoconf

# Install dependencies for AUGUSTUS
apt install -y libsqlite3-dev libmysql++-dev

# Install dependencies for AUGUSTUS comparative gene prediction mode (CGP)
apt install -y libgsl-dev libsuitesparse-dev liblpsolve55-dev

# Install dependencies for  the optional support of gzip compressed input files
apt install -y zlib1g-dev

# Install dependencies for bam2hints and filterBam 
apt install -y libbamtools-dev

# Install additional dependencies for htslib and samtools
apt install -y libbz2-dev liblzma-dev libncurses5-dev

# Install additional dependencies for bam2wig
apt install -y libssl-dev libcurl3-dev

# Install additional dependencies for homgenemapping and utrrnaseq
apt install -y libboost-all-dev
