language: generic
sudo: required

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

services:
  - docker

before_install:
  - printenv | grep -E '^TRAVIS_' > .env
  
script:
  - docker build -f Dockerfile -t augustus .
  - docker build -f Dockerfile-cgp-file -t augustus-cgp-file .
  - docker build -f Dockerfile-cgp-mysql -t augustus-cgp-mysql .
  - docker build -f Dockerfile-cgp-sqlite -t augustus-cgp-sqlite .
  - doxygen doxygen.conf

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: $TRAVIS_BUILD_DIR/doxygen/html
  github-token: $GITHUB_API_KEY
  on:
    branch: master
