// Generated by Bisonc++ V2.4.1 on Thu Dec 20 13:17:46 2007 +0100

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "parserbase.h"

// $insert scanner.h
#include "../scanner/scanner.h"



#undef Parser
class Parser: public ParserBase
{
 public:

  Parser(PhyloTree* tree): d_scanner(&d_val__), ptree(tree) {}
  Parser(PhyloTree* tree, std::istream* arg_yyin = 0, std::ostream* arg_yyout = 0):
	d_scanner(&d_val__, arg_yyin, arg_yyout), ptree(tree)
  {}
  Scanner d_scanner;
  PhyloTree *ptree;

  int parse();
       
    private:
        void error(char const *msg);    // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc

    // support functions for parse():
        void executeAction(int ruleNr);
        void errorRecovery();
        int lookup(bool recovery);
        void nextToken();
};

inline void Parser::error(char const *msg)
{
    std::cerr << msg << '\n';
}

// $insert lex
inline int Parser::lex()
{
   return d_scanner.yylex();

}

inline void Parser::print()      // use d_token, d_loc
{}


#endif
