// Generated by Bisonc++ V2.09.03 on Wed, 21 Mar 2012 21:16:32 +0100

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "parserbase.h"
// $insert scanner.h
#include "../scanner/scanner.h"


#undef Parser
class Parser: public ParserBase
{
    public:
    // $insert scannerobject
    Parser(PhyloTree* tree, std::istream &in):d_scanner(in), ptree(tree) {}
    Scanner d_scanner;
    PhyloTree *ptree;
        
        int parse();

    private:
        void error(char const *msg);    // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc

    // support functions for parse():
        void executeAction(int ruleNr);
        void errorRecovery();
        int lookup(bool recovery);
        void nextToken();
};

inline void Parser::error(char const *msg)
{
    std::cerr << msg << '\n';
}

// $insert lex
inline int Parser::lex()
{
    return d_scanner.lex();
}

// $insert print
inline void Parser::print()
{}

#endif
