#!/bin/bash

# Build bam2wig dependencies (htslib, bfctools, samtools)

git clone https://github.com/samtools/htslib.git ${TOOLDIR}/htslib
cd ${TOOLDIR}/htslib
autoheader
autoconf
./configure
make

git clone https://github.com/samtools/bcftools.git ${TOOLDIR}/bcftools
cd ${TOOLDIR}/bcftools
autoheader
autoconf
./configure
make

git clone https://github.com/samtools/samtools.git ${TOOLDIR}/samtools
cd ${TOOLDIR}/samtools
autoheader
autoconf -Wno-syntax
./configure
make
