# Generates BAM and SAM files used for demonstrating filterBam
#
# Created: 28-February-2012
# Last modified: 28-February-2012

######################################################
# Generation of Dummy datasets
######################################################

SAMFILES = example_1.sam
SCRIPT = sam2bam.sh

bam : $(SAMFILES)
	sh $(SCRIPT) $^
