'\" t
.\"     Title: aln2wig
.\"    Author: [see the "AUTHORS" section]
.\" Generator: Asciidoctor 1.5.5
.\"      Date: 
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "ALN2WIG" "1" "" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
aln2wig \- convert alignments to wig files
.SH "SYNOPSIS"
.sp
\fBaln2wig\fP [parameters] \-f filename
.SH "OPTIONS"
.sp
\fB\-f\fP
.RS 4
Input filename (in psl or shrimp format)
.RE
.sp
\fB\-s\fP
.RS 4
Use span notation
.RE
.sp
\fB\-t\fP
.RS 4
Name of the track
.RE
.SH "AUTHORS"
.sp
AUGUSTUS was written by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.
.SH "ADDITIONAL DOCUMENTATION"
.sp
An exhaustive documentation can be found in the file /usr/share/doc/augustus/README.md.gz.