'\" t
.\"     Title: bam2hints
.\"    Author: [see the "AUTHORS" section]
.\" Generator: Asciidoctor 1.5.5
.\"      Date: 
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "BAM2HINTS" "1" "" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
bam2hints \- convert mRNA\-to\-genome alignments in BAM format into a hint file for AUGUSTUS
.SH "SYNOPSIS"
.sp
\fBbam2hints\fP [parameters] \-\-in=example.bam \-\-out=hints.gff
.SH "OPTIONS"
.sp
The input BAM file must be sorted by target (=genome) sequence names and within the sequences by begin coordinates.
.SS "Parameters:"
.sp
\fB\-\-priority=n\fP/\fB\-p\fP
.RS 4
priority of hint group (set to 4)
.RE
.sp
\fB\-\-maxgaplen=n\fP/\fB\-g\fP
.RS 4
gaps at most this length are simply closed (set to 14)
.RE
.sp
\fB\-\-minintronlen=n\fP/\fB\-m\fP
.RS 4
alignments with gaps shorter than this and longer than maxgaplen are discarded (set to 32)
.RE
.sp
\fB\-\-maxintronlen=n\fP/\fB\-M\fP
.RS 4
alignments with longer gaps are discarded (set to 350000)
.RE
.sp
\fB\-\-MinEndBlockLen=n\fP/\fB\-b\fP
.RS 4
minimum length of a \(aqdangling\(aq exon (set to 8)
.RE
.sp
\fB\-\-maxQgaplen=n\fP/\fB\-q\fP
.RS 4
maximum length of gap in query (cDNA) sequence (set to 5)
.RE
.sp
\fB\-\-exonhints\fP/\fB\-x\fP
.RS 4
compute exonpart, exon and splice site hints in addition to intron hints (set to 0=Off). You should generate exonpart hints from RNA\-Seq using wiggle (.wig) input to wig2hints.
.RE
.sp
\fB\-\-ep_cutoff=n\fP/\fB\-e\fP
.RS 4
this many bp are cut off of each exonpart hint at end of alignment (set to 10)
.RE
.sp
\fB\-\-source=s\fP/\fB\-s\fP
.RS 4
source identifier (set to \(aqE\(aq)
.RE
.sp
\fB\-\-intronsonly\fP/\fB\-I\fP
.RS 4
only retrieve intron hints (e.g. because the exon(part) hints are retrieved by converting to a wig track, set to 1=On). Deprecated as this is the default now.
.RE
.sp
\fB\-\-nomult\fP/\fB\-n\fP
.RS 4
do not summarize multiple identical intron hints to a single one (set to 0=Off)
.RE
.sp
\fB\-\-remove_redundant\fP/\fB\-r\fP
.RS 4
only keep the strongest hint for a region (set to 0=Off)
.RE
.sp
\fB\-\-maxcoverage=n\fP/\fB\-C\fP
.RS 4
maximal number of hints at a given position (0: filtering deactivated). A high value causes long running time of AUGUSTUS in regions with thousands of cDNA alignments. (set to 0)
.RE
.sp
\fB\-\-ssOn\fP/\fB\-S\fP
.RS 4
include splice site (dss, ass) hints in output (set to 0=Off)
.RE
.sp
\fB\-\-trunkSS\fP/\fB\-T\fP
.RS 4
include splice sites hints from the ends of a truncated alignment (contig too short, set to 0=Off)
.RE
.sp
\fB\-\-score=f\fP/\fB\-s\fP
.RS 4
fill this number in in the score column (set to 0)
.RE
.sp
\fB\-\-maxgenelen=n\fP/\fB\-G\fP
.RS 4
alignments of the same clone are considered to be of the same gene if not separated by more than this (set to 400000). Alignments that span more than this are ignored, but better filter long introns through an alignment program.
.RE
.SH "AUTHORS"
.sp
AUGUSTUS was written by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.
.SH "ADDITIONAL DOCUMENTATION"
.sp
An exhaustive documentation can be found in the file /usr/share/doc/augustus/README.md.gz.
