'\" t
.\"     Title: checktargetsortedness
.\"    Author: [see the "AUTHORS" section]
.\" Generator: Asciidoctor 1.5.5.dev
.\"      Date: 
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CHECKTARGETSORTEDNESS" "1" "" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
checktargetsortedness \- check BAM file for sortedness
.SH "SYNOPSIS"
.sp
\fBcheckTargetSortedness\fP infile.bam
.SH "OPTIONS"
.sp
\(aqinfile.bam\(aq is the name of the BAM file to check for sortedness. The program will output a
short message describing the sortedness status of the file.
.SH "AUTHORS"
.sp
AUGUSTUS was written by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.
.SH "ADDITIONAL DOCUMENTATION"
.sp
An exhaustive documentation can be found in the file /usr/share/augustus/README.TXT.