'\" t
.\"     Title: consensusfinder
.\"    Author: [see the "AUTHORS" section]
.\" Generator: Asciidoctor 1.5.5.dev
.\"      Date: 
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CONSENSUSFINDER" "1" "" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
consensusfinder \- consensus finder
.SH "SYNOPSIS"
.sp
\fBconsensusFinder\fP input_fasta_file [options]
.SH "OPTIONS"
.sp
\fB\-l\fP
.RS 4
pattern length
.RE
.sp
\fB\-p\fP
.RS 4
p\-value for finding the significant strings
.RE
.sp
\fB\-d\fP
.RS 4
delta to find the relevant strings
.RE
.sp
\fB\-s\fP
.RS 4
starting position
.RE
.sp
\fB\-e\fP
.RS 4
ending position
.RE
.sp
\fB\-m\fP
.RS 4
no. of mismatches to consider while finding neighbours
.RE
.sp
\fB\-c\fP
.RS 4
string to consider for analysis
.RE
.sp
\fB\-n\fP
.RS 4
specify the number of consensus patterns to store
.RE
.sp
\fB\-t\fP
.RS 4
print the histogram
.RE
.SH "AUTHORS"
.sp
AUGUSTUS was written by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.
.SH "ADDITIONAL DOCUMENTATION"
.sp
An exhaustive documentation can be found in the file /usr/share/augustus/README.TXT.