'\" t
.\"     Title: curve2hints
.\"    Author: [see the "AUTHORS" section]
.\" Generator: Asciidoctor 1.5.5
.\"      Date: 
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CURVE2HINTS" "1" "" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
curve2hints \- tool to make exon segmentation and grouping the exons together to form AUGUSTUS hints
.SH "SYNOPSIS"
.sp
\fBcurve2hints\fP \-\-in=file \-\-outexons=out.gff \-\-c=int \-\-s=float
.SH "OPTIONS"
.sp
\fB\-\-in=s\fP
.RS 4
iput file is single file containing tracks in wig format
.RE
.sp
\fB\-\-outexons=s\fP
.RS 4
file for the output segmentaion
.RE
.sp
\fB\-\-c\fP
.RS 4
specify the threshold to distinguish between introns and exons in terms of coverage depths (default 4)
.RE
.sp
\fB\-\-s\fP
.RS 4
specify the ratio \fB(1\-lambda1)/(1\-lambda2)\fP It should be >1 (default 1.12)
.RE
.sp
\fB\-\-z\fP
.RS 4
specify the chunk size (default value 50000)
.RE
.sp
\fB\-\-r\fP
.RS 4
To enable re\-estimation of distribution from the output produced
.RE
.sp
\fB\-\-train_file\fP
.RS 4
Specify the gff file to be used for training the distributions.It should contain the position of both introns and exons
.RE
.sp
\fB\-\-bed_file\fP
.RS 4
Specify the output bedfile which contains the position of gene jumps (default: output.bed)
.RE
.sp
\fB\-\-augustus_hints\fP
.RS 4
Specify the output augustus hint file(default: augustus_hints.gff)
.RE
.SH "AUTHORS"
.sp
AUGUSTUS was written by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.
.SH "ADDITIONAL DOCUMENTATION"
.sp
An exhaustive documentation can be found in the file /usr/share/doc/augustus/README.md.gz.