'\" t
.\"     Title: getseq
.\"    Author: [see the "AUTHORS" section]
.\" Generator: Asciidoctor 1.5.5
.\"      Date: 
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "GETSEQ" "1" "" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
getseq \- retrieve genome sequences from MySQL and SQLite Databases
.SH "SYNOPSIS"
.sp
MySQL:
\&.br
  \fBgetSeq\fP [parameters] \-\-species=SPECIES \-\-seq=SEQUENCE \-\-dbaccess=dbname,host,user,passwd 
\&.br
SQLite:
\&.br
  \fBgetSeq\fP [parameters] \-\-species=SPECIES \-\-seq=SEQUENCE \-\-dbaccess=dbname.db \-\-speciesfilenames=SPECIESFILENAMES
.SS "Mandatory parameters"
.sp
\fB\-s\fP, \fB\-\-species=SPECIES\fP
.RS 4
SPECIES is the species identifier used when loading the sequence into the database.
.RE
.sp
\fB\-q\fP, \fB\-\-seq=SEQUENCE\fP
.RS 4
SEQUENCE is the ID of the sequence to retrieve.
.RE
.sp
\fB\-c\fP, \fB\-\-dbaccess=database\fP
.RS 4
MySQL:  dbname,host,user,passwd are the name of the SQL database, the host name or IP, the database user and password
\&.br
SQLite: the file name of the SQLite database (must contain a dot)
.RE
.sp
\fB\-f\fP, \fB\-\-speciesfilenames=SPECIESFILENAMES\fP
.RS 4
This parameter is only recognized for SQLite databases.
\&.br
SPECIESFILENAMES is the file where the species identifier and the related file names of the sequences are stored.
\&.br
format:
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
    Homo sapiens <TAB> /dir/to/genome/human.fa
    Mus musculus <TAB> /dir/to/genome/mouse.fa
.fi
.if n \{\
.RE
.\}
.SS "Additional options"
.sp
\fB\-a\fP, \fB\-\-start=n\fP
.RS 4
Retrieve subsequence starting at position N (coordinates are 1\-based).
.RE
.sp
\fB\-b\fP, \fB\-\-end=n\fP
.RS 4
Retrieve subsequence ending at position N (coordinates are 1\-based).
.RE
.sp
\fB\-r\fP, \fB\-\-rc\fP
.RS 4
Output the reverse complement of the sequence.
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Produce help message. Default Value: false
.RE
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
  MySQL:
    getSeq \-\-species=mouse \-\-seq=chr16 \-\-dbaccess=vertebrates,localhost,myuser,mypasswd
    getSeq \-\-species=human \-\-seq=chr21 \-\-start=32026 \-\-end=32085 \-\-rc \-\-dbaccess=vertebrates,localhost,myuser,mypasswd

  SQLite:
    getSeq \-\-species=mouse \-\-seq=chr16 \-\-dbaccess=vertebrates.db \-\-speciesfilenames=speciesfilenames.tsv
.fi
.if n \{\
.RE
.\}
.SH "AUTHORS"
.sp
AUGUSTUS was written by M. Stanke, O. Keller, S. König, L. Gerischer and L. Romoth.