# Makefile for auxprogs
#
# Created on: 16-October-2016
# Last modified on: 16-October-2016 by Katharina Hoff (katharina.hoff@gmail.com)

all:
	cd bam2hints; make;
	cd compileSpliceCands; make;
	cd filterBam; make;
	cd homGeneMapping; make;
	cd joingenes; make;
clean:
	echo `pwd`;
	cd bam2hints; make clean;
	echo `pwd`;
	cd compileSpliceCands; make clean;
	echo `pwd`;
	cd filterBam; make clean;
	echo `pwd`;
	cd homGeneMapping; make clean;
	echo `pwd`;
	cd joingenes; make clean;
	echo `pwd`;
